### ISSUE TITLE
Expert feature questions

### ISSUE THREAD

**Issue by bearinsuke** [hsd1503/ENCASE#3]
Hi,
Thanks for your contribution. Your work is really outstanding. 
I have a little question about your expert feature. Are these 3 kinds of features (statistical, signal, and medical) come from the long, short, QRS data? Plus, the link https://github.com/hsd1503/ENCASE/tree/master/code/featrues_*.py has expired. May you share another one?

Thanks,

**Comment by hsd1503** [comment]
Hi, the link shows format of filenames which points several code files (such as https://github.com/hsd1503/ENCASE/blob/master/code/features_long.py). You can find them in the code/ folder. Details of the features can be found in our papers. Thanks!

**Comment by bearinsuke** [comment]
Hi,
Thanks for your response. It helps a lot!
